// response-status.enum.ts
export enum ResponseStatus {
  MSG_SUCCESS = "Saved successfully",
  EXISTS = "Record already exists",
  ID_NOT_FOUND = "Id not found",
  ERROR = "Error occurred",
  STATUS_201 = "Saved successfully or Record already exists",
  STATUS_404 = "Record(s) not found",
  STATUS_500 = "Internal server error",
  API_SUMMARY = "Create Record",
  RECORD_NOT_FOUND = "Record(s) not found",
  STATUS_200 = "Record(s) fecthed successfully",
  STATUS_SUCCESS = "success",
  STATUS_ERROR = "error",
  UNEXCEPTED_ERROR = "Unexpected error",
  
  // Authentication specific statuses
  AUTH_SUCCESS = "Authentication successful",
  AUTH_FAILED = "Authentication failed",
  TOKEN_EXPIRED = "Token has expired",
  TOKEN_INVALID = "Invalid token",
  UNAUTHORIZED = "Unauthorized access",
  LOGIN_SUCCESS = "Login successful",
  LOGOUT_SUCCESS = "Logout successful",
  TOKEN_REFRESHED = "Token refreshed successfully",
  PROFILE_RETRIEVED = "Profile retrieved successfully",
  INVALID_CREDENTIALS = "Invalid email or password",
  USER_NOT_FOUND = "User not found",
  USER_INACTIVE = "User account is inactive",
  NO_AUTH_TOKEN = "No authentication token provided",
  NO_AUTH_COOKIE = "No authentication cookie provided",
  NO_BEARER_TOKEN = "No Bearer token provided",
  INVALID_TOKEN_USER_NOT_FOUND = "Invalid token: user not found",
  INVALID_EXPIRED_TOKEN = "Invalid or expired token",
  INVALID_EXPIRED_COOKIE = "Invalid or expired authentication cookie",
  INVALID_EXPIRED_BEARER = "Invalid or expired Bearer token",
}
